language: java
dist: trusty
postgresql: "9.5"
jdk:
  - oraclejdk8
  - openjdk8
services:
  - postgresql
before_script:
  - psql -c 'create database app_store_test;' -U postgres
  - psql -h localhost -d app_store_test -U postgres -p 5432 -a -q -f src/main/resources/db/migration/V1_0__appstore_create.sql
  - echo -e "Host github.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
  - "curl -H 'Cache-Control: no-cache' https://raw.githubusercontent.com/fossas/fossa-cli/master/install.sh | bash"
addons:
  sonarcloud:
    orgainization: "laffer1-github"
    token:
      secure: "IsN/oPwbwiZpAHu2MJU23OfdJGUfclqBwqi3s/jTKhxofnUqjLaNmRddE37WUKoYAIBCEXLsRqzDnhybsm+UyOGWU9GTosR0fPDjsBlE9ra17hPCwSYHM6C7gH1KcBQ4SZTsLeRTpkpKHlgcMbQZHu2KtziDDOKFAJofLhEweI6P9UWhohuybCUEDokdfOQEvVgyPF3NsOhHhtJlbx9P67Ux0V+IBx25cXHYOCWPKXg8/zQJsU4bL/lD6kkKdXvCbmJ+KsHnlMaKs+f5yG/I1PKtjVyKwHnYhUiINGq7bYF3VZxpX5f8/bEAul8xPqHDHR3mxNuvUMZINqjgK+eVDjCc5suOWDecTxLcdgDjhORb/iYBegPtmTBAGjjLIS3S5eUAZxhtF9iYbFXcGND3nfGOswlspeYMyQlotse+o6S2+J47t1anVEXQge14kVB0hnzJKtZHoYTqMPo7Vc8S8HwEj+y4NvM7/lbAvhuwYQbtyh714vykK76kFCQJ24gOTrhy8B+XHGsKCjvCAgNsuQwfzj9Un3BoFU4UZURQbFc7mRBHtileMN8SeKpAzm+obbBvLDN6B1btGDMR+lUIrrEvhb+KPKxpW18OGI+EXJbMCSCG3BVhU93JbRSOerTgyqbYXpcWSJc1PG2+at5NXJuxRvXaOVcXEC0y0YfJHWQ="

script:
  - fossa init
  - fossa analyze
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=org.midnightbsd:app-store
