spring:
  profiles.default: default
---
spring:
  profiles: default
  jackson:
    serialization:
      write-dates-as-timestamps: false
  flyway:
    baseline-on-migrate: true
    user: appstore
    password:
    url: jdbc:postgresql://db.midnightbsd.org/app_store
    table: schema_version
  datasource:
    url: jdbc:postgresql://db.midnightbsd.org/app_store
    jdbc-url: jdbc:postgresql://db.midnightbsd.org/app_store
    username: appstore
    password:
    hikari:
      jdbc-url: jdbc:postgresql://db.midnightbsd.org/app_store
      maximum-pool-size: 10
      minimum-idle: 1
  jpa:
    database: POSTGRESQL
    hibernate:
      ddl-auto: none
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
      use-new-id-generator-mappings: false
    generate-ddl: false
    show-sql: false
    properties:
     dialect: org.hibernate.dialect.PostgreSQLDialect
     hibernate:
       temp:
         use_jdbc_metadata_defaults: false
     javax:
       persistence:
         sharedCache:
           mode: ALL
  cache:
    type: REDIS
  redis:
    host: localhost
    port: 6379
    database: 0
  data:
    jest:
      uri: http://localhost:9200
      aws-region: us-east-1

eureka:
  client:
    serviceUrl:
     defaultZone: http://eureka.justjournal.com:8761/eureka/

server:
  tomcat:
    remote_ip_header: x-forwarded-for
    protocol_header: x-forwarded-proto

magus:
  baseUrl:  http://www.midnightbsd.org/magus/

search:
  package-item-index: pkgitem

---
spring:
  profiles: test
  flyway:
    baseline-on-migrate: true
  datasource:
    url: jdbc:postgresql://localhost/app_store_test
    username: postgres
    password:

---
spring:
  profiles: it
  flyway:
    baseline-on-migrate: true
  datasource:
    url: jdbc:postgresql://localhost/app_store_test
    username: postgres
    password:

---
spring:
  profiles: prod
  flyway:
    url: jdbc:postgresql://midnightbsd-app-store.c9or38nglwhm.us-east-1.rds.amazonaws.com/app_store?ssl=true&sslfactory=org.postgresql.ssl.NonValidatingFactory
  redis:
    host: midnightbsd-redis.c6ifkh.0001.use1.cache.amazonaws.com
    port: 6379
    database: 0
  data:
    jest:
      uri: https://vpc-mnbsd-3en4agwhc4ud7wmwuigo7aovwi.us-east-1.es.amazonaws.com:443/
      aws-region: us-east-1
  datasource:
    hikari:
      jdbc-url: jdbc:postgresql://midnightbsd-app-store.c9or38nglwhm.us-east-1.rds.amazonaws.com/app_store?ssl=true&sslfactory=org.postgresql.ssl.NonValidatingFactory
      maximum-pool-size: 10
      minimum-idle: 1
    jdbc-url: jdbc:postgresql://midnightbsd-app-store.c9or38nglwhm.us-east-1.rds.amazonaws.com/app_store?ssl=true&sslfactory=org.postgresql.ssl.NonValidatingFactory
    url: jdbc:postgresql://midnightbsd-app-store.c9or38nglwhm.us-east-1.rds.amazonaws.com/app_store?ssl=true&sslfactory=org.postgresql.ssl.NonValidatingFactory
    username: appstore
    password: 
cloud:
  aws:
    credentials:
      accessKey:
      secretKey:
    region:
      static: US_EAST_1

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
