spring:
  profiles:
    active: default
---
spring:
  profiles.default: default
---
spring:
  config:
    activate:
      on-profile: default
  jackson:
    serialization:
      write-dates-as-timestamps: false
  flyway:
    baseline-on-migrate: true
    user: appstoredev
    password:
    url: jdbc:postgresql://db.midnightbsd.org/app_store_dev
    table: schema_version
  datasource:
    url: jdbc:postgresql://db.midnightbsd.org/app_store_dev
    jdbc-url: jdbc:postgresql://db.midnightbsd.org/app_store_dev
    username: appstoredev
    password:
    hikari:
      jdbc-url: jdbc:postgresql://db.midnightbsd.org/app_store_dev
      maximum-pool-size: 10
      minimum-idle: 1
  jpa:
    database: POSTGRESQL
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    generate-ddl: false
    show-sql: false
    properties:
     dialect: org.hibernate.dialect.PostgreSQLDialect
     hibernate:
       jdbc:
         lob:
           non_contextual_creation
     jakarta:
       persistence:
         sharedCache:
           mode: ALL
  cache:
    type: REDIS
  elasticsearch:
    uris: http://localhost:9200

server:
  tomcat:
    remoteip:
      remote_ip_header: x-forwarded-for
      protocol_header: x-forwarded-proto

magus:
  baseUrl:  https://www.midnightbsd.org/magus/

search:
  package-item-index: pkgitem

---
spring:
  config:
    activate:
      on-profile: test
  flyway:
    baseline-on-migrate: true
  datasource:
    url: jdbc:postgresql://localhost/app_store_test
    username: postgres
    password:

---
spring:
  config:
    activate:
      on-profile: it
  flyway:
    baseline-on-migrate: true
  datasource:
    url: jdbc:postgresql://localhost/app_store_test
    username: postgres
    password:

---
spring:
  config:
    activate:
      on-profile: prod
  flyway:
    url: jdbc:postgresql://db.midnightbsd.org/app_store
  elasticsearch:
    uris: http://db.midnightbsd.org:9200
  datasource:
    hikari:
      jdbc-url: jdbc:postgresql://db.midnightbsd.org/app_store
      maximum-pool-size: 10
      minimum-idle: 1
    jdbc-url: jdbc:postgresql://db.midnightbsd.org/app_store
    url: jdbc:postgresql://db.midnightbsd.org/app_store
    username: appstore
    password:
