spring:
  profiles.default: default
---
spring:
  profiles: default
  jackson:
    serialization:
      write-dates-as-timestamps: false
  datasource:
    url: jdbc:postgresql://db.midnightbsd.org/app_store?ssl=true&amp;sslfactory=org.postgresql.ssl.NonValidatingFactory
    username: appstore
    password: 
    max-active: 10
    initial-size: 5
    max-idle: 5
    min-idle: 1
    test-while-idle: true
    test-on-borrow: true
    validation-query: SELECT 1
  jpa:
    database: POSTGRESQL
    hibernate:
      ddl-auto: none
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    generate-ddl: false
    show-sql: false
    properties:
     dialect: org.hibernate.dialect.PostgreSQLDialect
     hibernate:
       temp:
         use_jdbc_metadata_defaults: false
       cache:
         provider_class: org.hibernate.cache.EhCacheProvider
         use_second_level_cache: true
         use_query_cache: true
         region:
            factory_class: org.hibernate.cache.ehcache.EhCacheRegionFactory
            prefix: hibernate
     javax:
       persistence:
         sharedCache:
           mode: ALL
  cache:
    type: REDIS
  redis:
    host: localhost
    port: 6379
    database: 0

endpoints:
  hypermedia:
    enabled: true

eureka:
  client:
    serviceUrl:
     defaultZone: http://127.0.0.1:8761/eureka/

flyway:
  baseline-on-migrate: true

server:
  tomcat:
    remote_ip_header: x-forwarded-for
    protocol_header: x-forwarded-proto

magus:
  baseUrl:  http://www.midnightbsd.org/magus/

search:
  package-item-index: pkgitem

---
spring:
  profiles: test
  datasource:
    url: jdbc:postgresql://localhost/app_store_test
    username: postgres
    password:

flyway:
  baseline-on-migrate: true

---
spring:
  profiles: prod
  redis:
    host: midnightbsd-redis.c6ifkh.0001.use1.cache.amazonaws.com
    port: 6379
    database: 0
  datasource:
    url: jdbc:postgresql://midnightbsd-app-store.c9or38nglwhm.us-east-1.rds.amazonaws.com/app_store?ssl=true&amp;sslfactory=org.postgresql.ssl.NonValidatingFactory
    username: appstore
    password: 
cloud:
  aws:
    credentials:
      accessKey:
      secretKey:
    region:
      static: US_EAST_1

flyway:
  url: jdbc:postgresql://midnightbsd-app-store.c9or38nglwhm.us-east-1.rds.amazonaws.com/app_store?ssl=true&amp;sslfactory=org.postgresql.ssl.NonValidatingFactory
  
